printf "${red}ABOUT PUTIN${creset}:\n"
printf "============\n"
printf "  * ${yellow}Putin is a Development Environment Focused At Malwares, Offering Special Tools, Tricks And Bypasses, For Malware Development\n"
printf "  Targetting Windows, Linux, And Android\n\n${creset}"
printf "  * ${ucyan}Documentation${creset}: https://github.com/Mahmoud7Osman/Putin\n"
printf "  * ${ucyan}Developer${creset}    : Mahmoud Osman\n"
printf "  * ${ucyan}Telegram${creset}     : @BogdanoffTheWhale\n"
printf "  * ${ucyan}Youtube${creset}      : @TheCZone\n\n"
printf "${red}USAGE${creset}:\n"
printf "=====\n"
printf "  * Execute$yellow putin list commands$creset To List All Available Commands, Tools And Scripts\n"
printf "  * Execute$yellow putin list projects$creset To List All Of Your Projects\n"
printf "  * Execute$yellow Any Command$creset Without Any Parameters To Learn About It's Usage\n"
printf "\n${red}CAUTION$creset: We Are Not Responsible For Any Harmful Or Illegal Actions Out Of This Software, Please Consider Using it At Your Own Risk.!\n\n"
